config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='main')),
    path('', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import ProfileUpdateView, UserRegisterView, EmailConfirmationSentView, UserConfirmEmailView, \
    EmailConfirmedView, EmailConfirmationFailedView, generate_new_password, backup_pass

app_name = UsersConfig.name

urlpatterns = [

    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileUpdateView.as_view(), name='profile'),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('email-confirmation-sent/', EmailConfirmationSentView.as_view(), name='email_confirmation_sent'),
    path('confirm-email/<str:uidb64>/<str:token>/', UserConfirmEmailView.as_view(), name='confirm_email'),
    path('email-confirmed/', EmailConfirmedView.as_view(), name='email_confirmed'),
    path('confirm-email-failed/', EmailConfirmationFailedView.as_view(), name='email_confirmation_failed'),
    path('generate_new_password/', generate_new_password, name='generate_new_password'),
    path('backup_pass/', backup_pass, name='backup_pass'),
]

users/models.py
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import User, AbstractUser
from django.db import models
from django.apps import apps
from catalog.models import NULLABLE

class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Create and save a user with the given username, email, and password.
        """
        if not email:
            raise ValueError("The given username must be set")
        email = self.normalize_email(email)
        GlobalUserModel = apps.get_model(
            self.model._meta.app_label, self.model._meta.object_name
        )
        email = GlobalUserModel.normalize_username(email)
        user = self.model(email=email, **extra_fields)
        user.password = make_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='почта')
    phone = models.CharField(max_length=35, verbose_name='телефон', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='аватар', **NULLABLE)
    country = models.CharField(max_length=35, verbose_name='страна', **NULLABLE)
    token = models.CharField(max_length=15, verbose_name='токен', **NULLABLE)
    token_time = models.DateTimeField(auto_now_add=True, verbose_name='время создания токена', **NULLABLE)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    def __str__(self):
        return f'{self.email}'

users/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm, UserCreationForm

from users.models import User


class UserForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

users/views.py
import random

from django.contrib.auth import login
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import send_mail
from django.shortcuts import redirect, render
from django.urls import reverse_lazy, reverse
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views import View
from django.views.generic import UpdateView, CreateView, TemplateView

from config import settings
from users.forms import UserForm, UserRegisterForm
from users.models import User


class ProfileUpdateView(UpdateView):
    model = User
    form_class = UserForm
    success_url = reverse_lazy('users:profile')
    template_name = 'users/user_register.html'

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f'Страница пользователя: {self.object.email}'
        return context


class UserRegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy('users:login')
    template_name = 'users/user_register.html'
    success_message = 'Вы успешно зарегистрировались. Проверьте почту для активации!'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Регистрация на сайте'
        return context

    def form_valid(self, form):
        self.object = form.save()
        token = default_token_generator.make_token(self.object)
        uid = urlsafe_base64_encode(force_bytes(self.object.pk))
        activation_url = reverse_lazy('users:confirm_email', kwargs={'uidb64': uid, 'token': token})

        send_mail(
            'Подтверждение почты',
            f'Для подтверждения регистрации перейдите по ссылке: http://localhost:8000/{activation_url}',
            settings.EMAIL_HOST_USER,
            [self.object.email],
            fail_silently=False,
        )

        #send_mail(
            #subject='Подтверждение почты',
            #message=f'Для подтверждения регистрации перейдите по ссылке: http://localhost:8000/{activation_url}',
            #from_email=settings.EMAIL_HOST_USER,
            #recipient_list=[self.object.email],
            #fail_silently=False
        #)
        return redirect('users:email_confirmation_sent')


class UserConfirmEmailView(View):
    def get(self, request, uidb64, token):
        try:
            uid = urlsafe_base64_decode(uidb64)
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and default_token_generator.check_token(user, token):
            user.is_active = True
            user.save()
            login(request, user)
            return redirect('users:email_confirmed')
        else:
            return redirect('users:email_confirmation_failed')


class EmailConfirmationSentView(TemplateView):
    template_name = 'users/email_confirmation_sent.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Письмо активации отправлено'
        return context


class EmailConfirmedView(TemplateView):
    template_name = 'users/email_confirmed.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Ваш электронный адрес активирован'
        return context


class EmailConfirmationFailedView(TemplateView):
    template_name = 'users/email_confirmation_failed.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Ваш электронный адрес не активирован'
        return context


def generate_new_password(request, email=None):
    if not email:
        email = request.user.email
    new_password = ''.join([str(random.randint(0, 9)) for _ in range(12)])

    send_mail(
        subject='Вы сменили пароль',
        message=f'Ваш новый пароль: {new_password}',
        from_email=settings.EMAIL_HOST_USER,
        recipient_list=[email],
        fail_silently=False
    )
    user = User.objects.filter(email=email).first()

    user.set_password(new_password)
    user.save()
    return redirect(reverse('users:login'))


def backup_pass(request):
        if request.method == "POST":
            email = request.POST.get('email')
            generate_new_password(request, email=email)
        return render(request, 'users/backup_pass.html')

users/templates/users/backup_pass.html
{% extends 'catalog/base.html'%}

{% block content %}
    <div class="col-3"></div>
    <div class="col-6">
    <div class="uk-card">
        <div class="uk-card-header"></div>
        <div class="uk-card-body">
            <form method="POST" action="" class="form-floating">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="name">Имя</label>
                    <input type="text" name="email" class="form-control" id="email" placeholder="Почта" required>
                </div>

                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
            </form>
        </div>

    </div>
    </div>
{% endblock %}

users/templates/users/email_confirmation_failed.html
{% extends "catalog/base.html" %}

{% block content %}
<div class="alert alert-danger" role="alert">
    <h4 class="alert-heading">Ошибка подтверждения по электронной почте</h4>
    <p>Ссылка для подтверждения по электронной почте недействительна или срок ее действия истек. Пожалуйста, зарегистрируйтесь снова.</p>
</div>
{% endblock %}

users/templates/users/email_confirmation_sent.html
{% extends "catalog/base.html" %}

{% block content %}
<div class="alert alert-info" role="alert">
    <h4 class="alert-heading">Письмо подтверждения отправлено!</h4>
    <p>
        На ваш адрес электронной почты было отправлено письмо с подтверждением. Пожалуйста, проверьте свою электронную почту и нажмите на ссылку подтверждения, чтобы завершить регистрацию.
        Если письмо не пришло, проверьте папку спам.
    </p>
</div>
{% endblock %}

users/templates/users/email_confirmed.html
{% extends "catalog/base.html" %}

{% block content %}
<div class="alert alert-success" role="alert">
    <h4 class="alert-heading">Электронная почта подтверждена</h4>
    <p>Ваш адрес электронной почты успешно подтвержден. Спасибо за регистрацию! Можете войти на сайт</p>
</div>
{% endblock %}

users/templates/users/login.html
{% extends 'catalog/base.html' %}
{% block content %}
    <div class="col-6">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-success">Войти</button>
                        </form>
                    </div>
                    <div class="card-footer">
                        <a class="p-2 btn btn-outline-primary" href="{% url 'users:backup_pass' %}">Забыли пароль</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/user_register.html
{% extends 'catalog/base.html' %}
{% block content %}
    <div class="col-6">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-success">Сохранить</button>
                        </form>
                    </div>
                    <div class="card-footer">
                        <a href="{% url 'users:generate_new_password' %}" class="btn btn-danger">Сгенерировать
                            пароль</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}