catalog/urls.py
from django.urls import path
from django.views.decorators.cache import never_cache

from catalog.views import ProductListView, ProductDetailView, HomeListView, ContactListView, RecordListView, \
    RecordCreateView, RecordUpdateView, RecordDeleteView, RecordDetailView, toggle_activity, ProductCreateView, \
    ProductUpdateView, ProductDeleteView
from catalog.apps import CatalogConfig

app_name = CatalogConfig.name


urlpatterns = [
    path('', HomeListView.as_view(), name='home'),
    path('contact/', ContactListView.as_view(), name='contact'),
    path('home/', HomeListView.as_view(), name='home'),
    path('product/', ProductListView.as_view(), name='product_list'),
    path('product/<pk>/', ProductDetailView.as_view(), name='product'),
    path('product/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('products/create/', never_cache(ProductCreateView.as_view()), name='product_create'),
    path('product_update/<int:pk>', ProductUpdateView.as_view(), name='product_update'),
    path('product_delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),
    path('records/', RecordListView.as_view(), name='record_list'),
    path('records/<slug:slug>/', RecordDetailView.as_view(), name='record_detail'),
    path('records_create/', RecordCreateView.as_view(), name='create_record'),
    path('records_update/<slug:slug>/', RecordUpdateView.as_view(), name='update_record'),
    path('records_delete/<slug:slug>/', RecordDeleteView.as_view(), name='delete_record'),
    path('toggle/<slug:slug>/', toggle_activity, name='toggle_activity')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='main')),
    path('', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import ProfileUpdateView, UserRegisterView, EmailConfirmationSentView, UserConfirmEmailView, \
    EmailConfirmedView, EmailConfirmationFailedView, generate_new_password, backup_pass

app_name = UsersConfig.name

urlpatterns = [

    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileUpdateView.as_view(), name='profile'),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('email-confirmation-sent/', EmailConfirmationSentView.as_view(), name='email_confirmation_sent'),
    path('confirm-email/<str:uidb64>/<str:token>/', UserConfirmEmailView.as_view(), name='confirm_email'),
    path('email-confirmed/', EmailConfirmedView.as_view(), name='email_confirmed'),
    path('confirm-email-failed/', EmailConfirmationFailedView.as_view(), name='email_confirmation_failed'),
    path('generate_new_password/', generate_new_password, name='generate_new_password'),
    path('backup_pass/', backup_pass, name='backup_pass'),
]

catalog/models.py
from django.db import models
from transliterate import translit
from django.urls import reverse
from django.utils.text import slugify

NULLABLE = {'blank': True, 'null': True}

class Category(models.Model):
    name = models.CharField(max_length=150, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'
        ordering = ('name',)


class Product(models.Model):
    ACTIVE = 'Активна'
    NO_ACTIVE = 'Не активна'

    SELECT_STATUS = [
        (ACTIVE, 'Активна'),
        (NO_ACTIVE, 'Не активна'),
    ]
    name = models.CharField(max_length=150, verbose_name= 'наименование')
    description = models.TextField(verbose_name='описание')
    image = models.ImageField(upload_to='products/', verbose_name='изображение', **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    price = models.FloatField(verbose_name='Цена за покупку')
    create_date = models.DateField(verbose_name='Дата создания')
    change_date = models.DateField(verbose_name='Дата последнего изменения')
    status = models.CharField(max_length=50, default = NO_ACTIVE, choices = SELECT_STATUS, verbose_name='Статус')
    user = models.CharField(max_length=50, verbose_name='Создатель', **NULLABLE)

    def __str__(self):
        return f'{self.name}: {self.price}; {self.category}'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        ordering = ('name',)

class Contact(models.Model):
    name = models.CharField(max_length=150, verbose_name='Имя пользователя')
    phone = models.CharField(max_length=20, verbose_name='Номер телефона')
    message = models.TextField(verbose_name='Сообщение')

    def __str__(self):
        return f'{self.name} - {self.phone}'

    class Meta:
        verbose_name = 'контакт'
        verbose_name_plural = 'контакты'
        ordering = ('name',)

class Record(models.Model):
    title = models.CharField(max_length=150, verbose_name='Заголовок')
    slug = models.SlugField(max_length=150, unique=True,  verbose_name='Slug')
    content = models.CharField(max_length=500, verbose_name='Содержимое')
    preview = models.ImageField(upload_to='records/', **NULLABLE, verbose_name='Превью (изображение)')
    created_date = models.DateField(auto_now_add=True, verbose_name='Дата создания')
    published = models.BooleanField(default=False, verbose_name='Признак публикации')
    views_count = models.IntegerField(default=0, verbose_name='Количество просмотров')

    class Meta:
        verbose_name = 'запись'
        verbose_name_plural = 'записи'

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            transliterated_title = translit(self.title, 'ru', reversed=True)
            self.slug = slugify(transliterated_title, allow_unicode=True)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('catalog:record_detail', kwargs={'slug': self.slug})

    def toggle_published(self):
        self.published = not self.published
        self.save()

class Version(models.Model):
    name_of_product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Продукт')
    number_of_version = models.CharField(max_length=20, verbose_name='Номер версии')
    title_of_version = models.CharField(max_length=150, verbose_name='Название версии')
    actual_version = models.BooleanField(verbose_name='Признак текущей версии')

    class Meta:
        verbose_name = 'Версия'
        verbose_name_plural = 'Версии'

    def __str__(self):
        return self.title_of_version

catalog/forms.py
from django import forms

from catalog.models import Product, Version

FORBIDDEN_WORDS = ('казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар')


class ProductForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
    class Meta:
        model = Product
        fields = '__all__'

    def clean_name(self):
        cleaned_data = self.cleaned_data['name']
        if cleaned_data in FORBIDDEN_WORDS:
            raise forms.ValidationError('Запрещенное название')
        return cleaned_data

    def clean_description(self):
        cleaned_data = self.cleaned_data['description']
        if cleaned_data in FORBIDDEN_WORDS:
            raise forms.ValidationError('Запрещенное описание')
        return cleaned_data

class VersionForm(forms.ModelForm):


    is_active = forms.BooleanField(label='Признак текущей версии', required=False, widget=forms.CheckboxInput())
    class Meta:
        model = Version
        fields = '__all__'

    def clean_is_active(self):
        cleaned_data = self.cleaned_data['is_active']
        if cleaned_data and self.instance.product.version_set.filter(is_active=True).exclude(
                id=self.instance.id).exists():
            raise forms.ValidationError('Может существовать только одна активная версия.')
        return cleaned_data
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

catalog/views.py
from django.forms import inlineformset_factory
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views import generic

from catalog.forms import ProductForm, VersionForm
from catalog.models import Product, Contact, Record, Version, Category
from django.views.generic import ListView, DetailView, DeleteView, UpdateView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin

# Create your views here.

class AuthRequiredMixin(LoginRequiredMixin):
    login_url = '/login/'
class HomeListView(ListView):
    model = Product

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object_list'] = Product.objects.all()
        return context

class ContactListView(ListView):
    model = Contact

class ProductListView(LoginRequiredMixin, generic.ListView):
    model = Product
    extra_context = {'title': 'Список продукции', 'object_list': Product.objects.filter(status='Активна')}

    def get_object(self, queryset=None):
        return self.request.user

class ProductDetailView(LoginRequiredMixin,  generic.DetailView):
    model = Product
    permission_required = 'catalog.view_product'

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = context_data['object']
        context_data['versions'] = Version.objects.filter(name_of_product=self.object, actual_version=True)
        return context_data

class ProductCreateView(LoginRequiredMixin, PermissionRequiredMixin, generic.CreateView):
    model = Product
    fields = ('name', 'description', 'preview', 'category', 'price', 'date_create', 'date_change', 'status', 'creator')
    success_url = reverse_lazy('main:product_list')
    permission_required = 'catalog.add_product'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, PermissionRequiredMixin, generic.UpdateView):
    model = Product
    form_class = ProductForm
    template_name = 'catalog/product_form_with_formset.html'
    success_url = reverse_lazy('main:product_list')
    permission_required = 'catalog.change_product'

    def get_success_url(self, *args, **kwargs):
        return reverse('main:product_update', args=[self.get_object().pk])

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.user != self.request.user and not self.request.user.is_staff:
            raise Http404("Вы не являетесь владельцем этого товара")
        return self.object

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)
class ProductDeleteView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    model = Product
    success_url = reverse_lazy('main:product_list')
    def test_func(self):
        return self.request.user.is_superuser

    def get_object(self, queryset=None):
        return self.request.user



class RecordListView(ListView):
    model = Record
    queryset = Record.objects.filter(published=True)


class RecordCreateView(CreateView):
    model = Record
    fields = ('title', 'content', 'preview', 'published')
    success_url = reverse_lazy('catalog:record_list')


class RecordUpdateView(UpdateView):
    model = Record
    fields = ('title', 'slug', 'content', 'preview', 'published', 'views_count')

class RecordDetailView(DetailView):
    model = Record

    def get_object(self, queryset=None):
        obj = super().get_object(queryset=queryset)
        obj.views_count += 1
        obj.save()
        return obj
    def get_success_url(self):
        return self.object.get_absolute_url()


class RecordDeleteView(DeleteView):
    model = Record
    success_url = reverse_lazy('catalog:record_list')
    #def toggle_activity(request, slug):
        #record_item = get_object_or_404(Record, slug=slug)
        #record_item.toggle_published()
        #return redirect(reverse('catalog:record_detail', args=[record_item.slug]))


def toggle_activity(request, slug):
    record_item = get_object_or_404(Record, slug=slug)
    record_item.toggle_published()
    return redirect(reverse('catalog:record_detail', args=[record_item.slug]))

catalog/templates/catalog/base.html
<!DOCTYPE html>
<html>
<head>
    <title>Домашняя страница</title>
    <style>
        main {
            margin-top: 150px;
        }
    </style>
</head>

<body>
<header>
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="/home/">Товары</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
        {% include 'catalog/includes/inc_main_menu.html' %}
        </div>
      </nav>
    </header>
   <main role="main">
   <div class="container marketing">

        <!-- Three columns of text below the carousel -->
        <div class="row">
            {% block content %}
            {% endblock %}
        </div><!-- /.row -->
   </main>
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</body>
</html>

catalog/templates/catalog/contact.html
{% extends 'catalog/base.html' %}
<body>
    {% block content %}
    <h1>Обратная связь</h1>
    <p>Заполните эту форму, чтобы связаться с нами.</p>
    <form>
        <label for="name">Имя:</label>
        <input type="text" id="name" name="name"><br><br>
        <label for="email">Email:</label>
        <input type="email" id="email" name="email"><br><br>
        <label for="message">Сообщение:</label>
        <textarea id="message" name="message"></textarea><br><br>
        <input type="submit" value="Send">
    </form>
    {% endblock %}
</body>
</html>

catalog/templates/catalog/product.html
{% extends 'catalog/base.html' %}


{% block content %}

    <div class="col">
        <div class="card">
            <div class="card-body">
                <table class="table">
                    <tr>
                        <td>Наименование</td>
                        <td>{{ title }}</td>
                    </tr>
                    <tr>
                        <td>Описание</td>
                        <td>{{ desc }}</td>
                    </tr>
                    <tr>
                        <td>Категория</td>
                        <td>{{ category }}</td>
                    </tr>
                    <tr>
                        <td>Цена</td>
                        <td>{{ price }} руб</td>
                    </tr>
                    <tr>
                        <td>Дата создания</td>
                        <td>{{ create_date }}</td>
                    </tr>
                    <tr>
                        <td>Дата изменения</td>
                        <td>{{ change_date }}</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
{% endblock %}
</main>
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</body>
</html>

catalog/templates/catalog/product_create.html
{% extends 'catalog/base.html' %}
{% block content %}
<html>
<head>
    <title>Создать продукт</title>
</head>
<body>
    <h1>Создать новый продукт</h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Создать</button>
    </form>
</body>
</html>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}


{% block content %}

     {% load tags %}
    <div class="container">
        <div class="card text-center">
            <div class="card-header">
                <h1 class="card-title mb-0">{{ object.name }}</h1>
                <small class="text-muted">{{ object.category }}</small>
            </div>
            <img class="card-img-top mx-auto mt-3" src="{% mediapath object.image %}" alt="Card image cap"
                 style="width: 300px; height: 300px;">
            <div class="card-body">
                <p class="lead">{{ object.description }}</p>
                <h4 class="card-title">{{ object.price }} руб.</h4>
                <a href="#" class="btn btn-primary">Купить</a>
                <a href="{% url 'catalog:product_list' %}" class="btn btn-info">Каталог товаров</a>
            <br><br>
                <a href="{% url 'catalog:product_update' object.pk %}" class="btn btn-outline-warning">Изменить продукт</a>
                <a href="{% url 'catalog:product_delete' object.pk %}" class="btn btn-outline-danger">Удалить продукт</a>
            </div>
            <div class="card-footer">
                <small class="text-muted">{{ object.changed_date | date }}</small>
            </div>
        </div>
    </div>
{% endblock %}
</main>
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</body>
</html>

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}
{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-8 col-md-6 col-lg-4 bg-light p-3 rounded">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <div class="form-group text-center">
                                <button class="btn btn-success mt-3" type="submit">Сохранить</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/product_form_with_formset.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col">
        <form class="row" method="post">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">

                        {% csrf_token %}
                        {{ form.as_p }}
                        <input type="submit" class="btn btn-success"
                               value="{% if object %}Сохранить{% else %}Создать{% endif %}">

                    </div>
                    <div class="card-footer">
                        <a href="{% url 'catalog:product_list' %}" class="btn btn-primary"><< Назад</a>
                    </div>
                </div>
            </div>

            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        Версия
                    </div>
                    <div class="card-body">
                        <table class="table">
                            {{ formset.management_form }}
                            {% for form in formset.forms %}
                                <tr class="subject-form">
                                    <td>{{ form.as_p }} </td>
                                </tr>
                            {% endfor %}
                        </table>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

catalog/templates/catalog/product_form_with_version.html
{% extends 'catalog/base.html' %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        <div class="row justify-content-center">
            <div class="col-sm-6 col-md-4 ml-3 mr-1 mb-3">
                <div class="card shadow-sm">
                    <div class="card-header text-center">
                        Продукты
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-md-4 mb-3">
                <div class="card shadow-sm">
                    <div class="card-header text-center">
                        Версии
                    </div>
                    <div class="card-body">
                       <table class="table">
                            {{ formset.management_form }}
                            {% for form in formset.forms %}
                                <tr class="version-form">
                                    <td>{{ form.as_p }}</td>
                                </tr>
                            {% endfor %}
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="form-group text-center">
            <button class="btn btn-success mt-3" type="submit">Сохранить</button>
        </div>
    </form>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}

{% block content %}
        <div class="container" style="text-align: left">
                <a href="{% url 'catalog:product_create' %}" class="btn btn-outline-primary">Создать продукт</a>
        </div>
    {% for object in object_list %}
        {% include 'catalog/includes/inc_product_card.html' %}
    {% endfor %}
{% endblock %}
{% block content_1 %}
    <div class="col-6 col-md">
    <h5>Категории</h5>
        {% for obj in category_list %}
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">{{ obj.name }}</a></li>
            </ul>
        {% endfor %}
    </div>
{% endblock %}
   </main>
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</body>
</html>

catalog/templates/catalog/product_update.html
{% extends 'catalog/base.html' %}
{% block content %}
<html>
<head>
    <title>Редактировать продукт</title>
</head>
<body>
    <h1>Редактировать продукт</h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
    </form>
</body>
</html>
{% endblock %}

catalog/templates/catalog/record_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="container">
        <h2 class="mt-4 mb-4 text-center">Подтвердите удаление</h2>
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data" class="mt-3">
                            {% csrf_token %}
                            <p>
                                Вы уверены, что хотите удалить "{{ object.title }}"?
                            </p>
                            <div class="row justify-content-center">
                                <a href="{% url 'catalog:record_list' %}" class="btn btn-secondary mr-3">Вернуться к
                                    записям</a>
                                <button class="btn btn-danger" type="submit">Удалить</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/record_detail.html
{% extends 'catalog/base.html' %}

{% block content %}
    {% load tags %}
    <div class="container">
        <div class="card text-center">
            <div class="card-header">
                {{ object.title }}
            </div>
            <div class="card-body">
                <h5 class="card-title">{{ object.content }}</h5>
                <img src="{% mediapath object.preview %}" class="card-img-top mx-auto d-block" alt=""
                     style="width: 300px; height: 300px;">
                <p class="card-text">Просмотры: {{ object.views_count }}</p>
                {% if perms.app.change_record %}
                    <a href="{% url 'catalog:update_record' object.slug %}" class="btn btn-warning">Изменить
                        запись</a>
                {% endif %}
                {% if perms.app.delete_record %}
                    <a href="{% url 'catalog:delete_record' object.slug %}" class="btn btn-danger">Удалить
                        запись</a>
                {% endif %}
                <br><br>
                <a href="{% url 'catalog:record_list' %}" class="btn btn-secondary">Все записи</a>
                <a href="{% url 'catalog:toggle_activity' object.slug %}" class="btn btn-outline-danger">Снять с
                    публикации</a>
            </div>
            <div class="card-footer text-muted">
                <p class="card-text">
                    Создана: {{ object.created_date }}<br>
                    Опубликована: {{ object.published }}
                </p>
            </div>
        </div>
    </div>


{% endblock %}

catalog/templates/catalog/record_form.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-8 col-md-6 col-lg-4 bg-light p-3 rounded">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <div class="form-group text-center">
                                <button class="btn btn-success mt-3" type="submit">Сохранить</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/record_list.html
{% extends 'catalog/base.html' %}

{% block content %}
    {% load tags %}
    <div class="container">
        <h1 class="text-center">Блог</h1>
        <table class="table table-striped">
            <thead class="thead-dark">
            <tr>
                <th scope="col" style="text-align: center">ID</th>
                <th scope="col" style="text-align: center">Заголовок</th>
                <th scope="col" style="text-align: center">Содержание</th>
                <th scope="col" style="text-align: center">Превью</th>
                <th scope="col" style="text-align: center">Просмотры</th>
                 <th scope="col" style="text-align: center"></th>
            </tr>
            </thead>
            <tbody class="table-group-divider table-divider-primary">
            {% for object in object_list %}
                {% if object.published %}
                    <tr>
                        <th scope="row">{{ object.pk }}</th>
                        <td>{{ object.title }}</td>
                        <td>{{ object.content|truncatechars:100 }}</td>
                        <td>
                            <img src="{% mediapath object.preview %}" class="rounded mx-auto d-block" alt=""
                                 height="100">
                        </td>
                        <td style="text-align: center">{{ object.views_count }}</td>
                        <td>
                            <a href="{% url 'catalog:record_detail' object.slug %}" class="btn btn-info btn-sm">
                                К записи</a>
                        </td>
                    </tr>
                {% endif %}
            {% endfor %}
            </tbody>
        </table>
        <div class="container" style="text-align: center">
            <a href="{% url 'catalog:create_record' %}" class="btn btn-outline-secondary btn-lg my-3"
               style="border-radius: 25px; padding: 10px 25px; font-size: 20px; font-weight: bold;">
                Создать запись
            </a>
        </div>
    </div>
{% endblock %}